apiVersion: v1
kind: Service
metadata:
  name: sonarqube-sonarqube
  namespace: sonarqube
spec:
  selector:
    app: sonarqube
    release: sonarqube
  ports:
    - name: http
      port: 9000
      targetPort: 9000
  type: LoadBalancer

